# Generated by Django 3.1.5 on 2021-01-07 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('type', models.CharField(default=None, max_length=10)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('code', models.CharField(default=None, max_length=5)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
