# Generated by Django 3.1.5 on 2021-01-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verify_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verify',
            old_name='status',
            new_name='isVerified',
        ),
    ]
