# Generated by Django 3.1.5 on 2021-01-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210112_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='isVerified',
        ),
    ]
