# Generated by Django 3.1.5 on 2021-01-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
    ]
