# Generated by Django 3.1.5 on 2021-01-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20210111_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
