# Generated by Django 3.1.5 on 2021-01-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_auto_20210111_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='isMilitary',
            field=models.BooleanField(default=False),
        ),
    ]
