# Generated by Django 3.1.5 on 2021-01-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_advertisement_ismilitary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-id']},
        ),
    ]
